### PR TITLE
Add tests to validate HTML and pageUrl

### PR DESCRIPTION
**Pull request by brianamarie**
These tests will prohibit anything from passing a test or being merged that isn't the correct syntax for a github pages site. 

@crichID @hectorsector @beardofedu @hollenberry for 👀 and 👍

### CODE REVIEW

**Comment by crichID** [comment]
@brianamarie this looks :sparkles: to me. Thank you for tackling this update to our tests!

**Comment by brianamarie** [comment]
Note: to test this
- Pull this branch locally
- Create a file that would break the test (or not break the test) 
- Run `ruby script/test_validateHtml.rb` and see what happens
- You can also push up to this branch to see if Travis will catch the failure/success

I'd love one person to test this by trying to break it as my test writing experience is limited 😊

**Comment by crichID** [comment]
@brianamarie I pushed a few commits just to see if I could make it pass and fail. There are some other issues with files in the repo (one I can't find) but I did finally get a failure with crichID.com. One challenge with that, what if they use a custom domain for their pages?

I think what we really want is to validate they gave us a correct URL - right? Could we do that with [HTMLProofer](https://github.com/gjtorikian/html-proofer)?

**Comment by brianamarie** [comment]
@crichID I've started messing with HTML-proofer, as you can see in some of the more recent commits. 

I think the main goal is that it's a valid URL, **but** with how the site is currently building pins from these `.yaml` files, it will break if there is `https://` included. It needs to have only the text of the url like `github.github.io` included for it to work. Does that make sense?

I'm not certain that HTML-proofer can do this but I will look into it. We _may_ be put to a decision to either 
- Minimize functionality and require users to enter the github pages URL
- Rewrite the jekyll so it can include different formats of URLs

**Comment by brianamarie** [comment]
A few thoughts here before I log off for the evening - 

- I'm getting failures for two files that don't exist in the repo?
- HTML-proofer is passing even though there is an invalid URL for billyyumyum2x2

I will return to this when my brain is fresher.

**Comment by brianamarie** [comment]
@crichID I _think_ this is working now.

- I don't know what those merge conflicts are about at all, but those files gave me trouble so I created valid files of the same names and fixed the build. Problem is, now I think the merge conflict files are invisible? 👻 
- HTML-proofer checks all URLs in the pages and will cause Travis to fail if it's not a valid URL
- I deleted some pins that didn't have valid URLs. We can get them back if we want by reverting e4d7f05

**Comment by brianamarie** [comment]
Still a small issue that we need to resolve: If a user includes 'http' at the beginning of their link, it will not work.

**Comment by hollenberry** [comment]
So far, I have done the following tests:
1. Failed due to gcarlos [nil] -> @brianamarie fixed.
2. Passed, but shouldn't. I mixed the date to 12-06-2016. This will be addressed in another PR. 
3. I changed my name so the URL is invalid. This broke as expected.

**Comment by brianamarie** [comment]
Thank you so much for testing @hollenberry!! I am going to merge this now because there are new pins with incorrect urls being merged every day. If anyone notices a problem, please let me know so we can correct quickly. 😄

**Pull request merged**
