### PR TITLE
Added user info page

### PR DESCRIPTION
**Pull request by nishant19**
Added a new .yaml file/page which contains my github handle , today's date .

### CODE REVIEW

**Comment by nishant19** [comment]
@githubteacher What is wrong with my file ?

**Comment by nishant19** [comment]
@githubteacher , what is the issue with my file ? The test seems to fail , everytime.

**Comment by hollenberry** [comment]
Hey @nishant19 ! 

There are a few errors:
- You'll need to remove `TODAYS DATE` from the timestamp.
- You need to add 3 dashes to the bottom of your code.
- It looks like the tests are failing because your web page no longer exists or pages has not been enabled on the repository. If you have created your repository, please go to the repository **settings** and scroll down to the **pages** section. Using the drop-down, select the **master** branch to render your website. When you have finished this, your web page will display at the link shown at the top of the pages section. 
- Add a new line below the 3 dashes that you'll add.

**Comment by hollenberry** [comment]
I am going to go ahead and close this pull request since your page is not currently enabled. If you would like to finish this activity, please feel free to re-open this pull request after you have enabled pages on your repository.

**Pull request closed without merging**
