### PR TITLE
Adding a pull request to support recent changes

### PR DESCRIPTION
**Pull request by OldHWGuy**
Updated with name, url, and timestamp

### CODE REVIEW

**Comment by OldHWGuy** [comment]
cgithubapture

**Comment by brianamarie** [comment]
Hm, @OldHWGuy It looks to be the URL to the portfolio not working. Very interesting...let me know how you want to move forward. I see two options:
- Exploring why the OldHwGuy.github.io/portfolio isn't working, and fix it
- Change the URL here to something generic, like github.com, so the tests pass

**Comment by OldHWGuy** [comment]
Thank you, it might be excessive AND unnecessary but i might explore both, as long as it does not take away from what you need to do.  Since in this case I am learning github, I am a pretty immersive so looking at both would give perspective into how things operate.Obviously not tonight, I want to look at the discourse timeline, ours as well as that on github as a understanding of cause and effect.If you are no busy tomorrow evening i may call unless life intercedes.

**Comment by brianamarie** [comment]
Okay, well let me know! (For other trainers, this is my dad 😸)

**Comment by crichID** [comment]
:wave: Hi @OldHWGuy - we are super excited you are taking the training. You are now officially **The Coolest Dad** :TM:

**Comment by OldHWGuy** [comment]
Thanks for the props, just have to stay with it.

**Comment by crichID** [comment]
Hi @OldHWGuy :wave: it looks like the tests are failing because pages has not been enabled on the repository yet. Here is how you can fix it:

1. in the repository https://github.com/OldHWGuy/Portfolio click **Settings** 
2. Scroll down to the **Pages** section. 
3. Using the drop-down, select the **master** branch to render your website. 
4. When you have finished this, your web page will display at the link shown at the top of the pages section. Just give it a few minutes to finish building!

Let us know if we can help!

**Comment by OldHWGuy** [comment]
Hi @crichID ,
 Thanks for your help, I did as instructed, saw the web site come up with 
Hello World My name is OldHWGuy
If this is correct I am good to go.
Thanks again

**Comment by OldHWGuy** [comment]
Looks like i still have issues

**Comment by crichID** [comment]
@OldHWGuy Hmmmm ... so this is interesting. If you try to access the site with https://OldHWGuy.github.io/portfolio (lowercase p), you get a 404:

screen shot 2017-03-24 at 10 47 53 pm
 
But if you access https://OldHWGuy.github.io/Portfolio (uppercase P), it works (even though it strips your username of caps):

screen shot 2017-03-24 at 10 44 17 pm

It defies all logic, but can you try changing the p in your file to uppercase and let's see if it works?

**Comment by OldHWGuy** [comment]
Cynthia,Thanks I tried what you did, same illogcal result.  Went to look at code and did not fined the snippt in question, not sure if is gone or if I did not look in the correct place.  I looked in repository OldHWGuy/Portfolio: in README.md, _config.yml, and index.html.

**Comment by crichID** [comment]
@OldHWGuy it looks like you have successfully merged a different pull request so I am going to go ahead and close this one out as a duplicate. Awesome work :tada:

**Pull request closed without merging**
