### PR TITLE
add Spectre503 page

### PR DESCRIPTION
**Pull request by Spectre503**

### CODE REVIEW

**Comment by Spectre503** [comment]
Could anyone explain why the blank line missing after the last `---` being the cause of the checks not passing?

**Comment by rayjames** [comment]
Hi, yes, I ran into the same problem.  It should actually read "missing end of line".  I had to go in and add a blank line at the bottom of the file and then it worked.  That type of file is always supposed to have an end of line (blank line) at the bottom.  Hope that helps.

**Comment by Spectre503** [comment]
@rayjames: Yes, I only figured it out once I entered in the code editor here in the site. This error doesnt show in the Desktop app.

**Comment by Spectre503** [comment]
@hectorsector: Thanks

**Pull request merged**
