### PR TITLE
Added page

### PR DESCRIPTION
**Pull request by Bauke777**

### CODE REVIEW

**Comment by Bauke777** [comment]
Added my own page

**Comment by Bauke777** [comment]
Fixed document start and end in page

**Comment by 22mayank** [comment]
page URL should only be ur username.github.io
for example mine is pageUrl: 22mayank.github.io

**Comment by 22mayank** [comment]
The yaml page should be of 6 lines. after the 1st five line hit enter to add a blank line. and while pulling request in assignes add "assign to yourself"

**Comment by Bauke777** [comment]
Added line to document

**Comment by 999hao** [comment]
photo 2018_02_12 15-43-27
photo 2018_02_12 15-43-37

**Comment by 22mayank** [comment]
There it is

**Comment by Bauke777** [comment]
@22mayank Thank you so much!

**Pull request merged**
