### PR TITLE
Adding my page to the showcase

### PR DESCRIPTION
**Pull request by EdwinAVA**
:racing_car:

### CODE REVIEW

**Comment by EdwinAVA** [comment]
Closes #2431

**Comment by EdwinAVA** [comment]
@githubteacher  I don't kwow what travis is doing during the test. But it throws the following 
image

**Comment by EdwinAVA** [comment]
I think that the lbejosano.github.io's page is failing in some way and it is necessary to delete him from the list :sweat_smile:

**Comment by johnstond** [comment]
@EdwinAVA 
Your PR is now ready to merge.

**Review by beebus — APPROVED** [review]

**Pull request merged**
