### PR TITLE
Add ting11222001.yaml 's file: Issues #3119

### PR DESCRIPTION
**Pull request by ting11222001**
What do you think @githubteacher ?

### CODE REVIEW

**Comment by ting11222001** [comment]
I found the below message in job log (from travis-ci):

  => 13:         assert_not_nil(HTMLProofer.check_links([s]).run, path)
============
Finished in 119.105578668 seconds.
1 tests, 637 assertions, 0 failures, 1 errors, 0 pendings, 0 omissions, 0 notifications
0% passed

So what do you think @githubteacher?

**Comment by Groiq** [comment]
I've looked at the source code of https://ting11222001.github.io/ and noticed it's missing the proper HTML structure.

Should be something like this::

```
<html>
<head>
<title>Hello world!</title>
</head>

<body>
<h1> Hellow World! </h1>

<p> My username is ting11222001. </p>
</body>

</html>
```
but is only

```
<h1> Hellow World! </h1>

<p> My username is ting11222001. </p>
```

I don't quite understand what the travis checks are testing, but maybe they check for valid html in the user page.

**Comment by johnstond** [comment]
This error was due to spelling, like most other PR in this course.

**Comment by johnstond** [comment]
@ting11222001 
Your PR awaits.

**Pull request merged**
