### PR TITLE
Introducing howtoprogrambirds page to class repo

### PR DESCRIPTION
**Pull request by howtoprogrambirds**

### CODE REVIEW

**Comment by howtoprogrambirds** [comment]
@githubteacher What am i doing wrong?

**Comment by r5atom** [comment]
@howtoprogrambirds it seems you are hitting the same wall as in issue #546. Have a look at the `Details` in the build by Travis CI?

**Comment by brianamarie** [comment]
Hi @howtoprogrambirds! I'm sorry you were having a problem with the build - it wasn't your fault. Your work is great, but some other links had been changed since they were added to the showcase. Go ahead and merge whenever you're ready! 😄

**Comment by howtoprogrambirds** [comment]
@r5atom What do i have to do, I do not understand the travis ci error (That is writtin in Details).

**Comment by howtoprogrambirds** [comment]
@brianamarie Thaanks!! 🎉

**Pull request merged**
