### PR TITLE
Add cool data from AlgusDark

### PR DESCRIPTION
**Pull request by AlgusDark**
Only cool data on YAML

### CODE REVIEW

**Comment by Rheriel** [comment]
💯

**Comment by brianamarie** [comment]
@AlgusDark  your code looks perfect! Please go ahead and click the big green button below to **Merge pull request**. In an effort to keep things in this repository clean, I will merge this if it is still open in a few days.

**Comment by AlgusDark** [comment]
@brianamarie Any idea why it was failling the tests?

**Comment by brianamarie** [comment]
@AlgusDark Yes, I think that someone had merged their page in and then deleted the repository that their entry was pointing to. So, the tests were failing since a webpage went to 404, but it had nothing to do with your code. 😄

**Pull request merged**
