### PR TITLE
sjdeak-add-page

### PR DESCRIPTION
**Pull request by sjdeak**
add me

### CODE REVIEW

**Comment by beardofedu** [comment]
@sjdeak it looks like the tests are failing because your web page no longer exists or pages has not been enabled on the repository. If you have created your repository, please go to the repository **settings** and scroll down to the **pages** section. Using the drop-down, select the **master** branch to render your website. When you have finished this, your web page will display at the link shown at the top of the pages section. I am going to go ahead and close this pull request since your page is not currently enabled. If you would like to finish this activity, please feel free to re-open this pull request after you have enabled pages on your repository.

**Comment by sjdeak** [comment]
The problem may not be associated with my pages. I create a new branch from master today and my pull request got merged. Thanks a lot for your help, Learn-by-doing with the on-demand tutorials is so cool.

**Comment by beardofedu** [comment]
@sjdeak Feel free to close this PR and delete the branch if you were able to merge in another branch. Glad you like the class 👍

**Comment by crichID** [comment]
@sjdeak it looks like this is a duplicate, so I am going to go ahead and close this one out!

**Pull request closed without merging**
