### PR TITLE
Create BunnyHouse.yaml

### PR DESCRIPTION
**Pull request by bunnyHouse**

### CODE REVIEW

**Comment by bunnyHouse** [comment]
@beardofedu I need some help...

**Comment by bunnyHouse** [comment]
@githubteacher give me a hand please...

**Comment by beardofedu** [comment]
@bunnyHouse you are all set to merge. The errors you were encountering were not related to your work, so you were doing everything correctly. 👍

**Comment by bunnyHouse** [comment]
@beardofedu thanks a lot~

**Pull request merged**
