### PR TITLE
Master

### PR DESCRIPTION
**Pull request by Dan-Donovan**

### CODE REVIEW

**Comment by hectorsector** [comment]
@vorador it looks like you mistakenly reversed the `base:` and `compare:` branches when you created the Pull Request. [These instructions](https://services.github.com/on-demand/github-desktop/14/) might help. I suggest you close this PR, and open a new one with `base:` set to `master` and `compare:` set to `Dan-Donovan-add-pages`. Let me know if you need any help with this!

**Comment by hectorsector** [comment]
Apologies @Dan-Donovan I just saw your previous PR #352 -- you can safely close this PR in favor of that one. I'll leave you a comment there to let you  know how to get it working.

**Comment by hectorsector** [comment]
> Did I break something for everyone?

Not at all! Git makes it hard for one person to break stuff for everyone. All you did in this PR is to try to bring in the changes from `master` into your branch, when we want to do it in reverse. So go ahead and close this PR and then continue working on #352.

**Comment by vorador** [comment]
@hectorsector Sorry, I don't understand. My Pull Request is #360 and it's already merged into master. Or at least I think so. :s

**Comment by hectorsector** [comment]
@vorador it sure is! I was only looking at the open PRs. If it's ok with you, then I'll close this one and #352

**Pull request closed without merging**
