### PR TITLE
Sravankml addpage

### PR DESCRIPTION
**Pull request by sravankml**
Make my page

### CODE REVIEW

**Comment by sravankml** [comment]
merging

**Comment by sravankml** [comment]
merging

**Comment by crichID** [comment]
@sravankml a few things:

- You had two files in your pull request, I removed one of the files since you should only have one for this activity.
- You will need to put the file in the correct folder: `_pages`
- You will need to remove the text on the last line that reads: `iam unableto merge`
- You will need one blank line at the end of your file (after the ---)

After you do these things, please commit your changes and let the checks run again.

**Comment by brianamarie** [comment]
Hi @sravankml!  If you don't make the changes by the end of the week, I'll go ahead and make them so we can keep the repository clean. 😄 Let me know if you need any help.

**Comment by brianamarie** [comment]
@sravankml  thank you for checking out our [on-demand classes](https://services.github.com/on-demand/). Since this file is not valid per the examples in the course, I am going to go ahead and close this Pull Request. If you would like to complete the activity, please feel free to re-open this Pull Request or start again. If you have any questions, please let us know!

**Pull request closed without merging**
