### PR TITLE
Xe ctvi add page

### PR DESCRIPTION
**Pull request by XeCtvi**
Renamed branch name

### CODE REVIEW

**Comment by XeCtvi** [comment]
@githubteacher , it seems like site "AbdollahRida.github.io" 404 issue failed my case, pls take a look. Thanks.

**Comment by Angelluc** [comment]
Hi XeCtvi I think if you retry your pull request for adding your page it will succeed now as there was an error on another page which is now deleted

**Comment by crichID** [comment]
@XeCtvi since @Angelluc fixed this  in  #1765 I went ahead and merged master into your branch. This should fix the file that is causing the build to fail and allow your checks to pass.

**Comment by hollenberry** [comment]
@XeCtvi  Your PR is great! Nice identification of build failures as well. I went ahead and removed the  extra files that were causing the build to fail and you should be all set to merge! Please go ahead and click that big green "Merge Pull Request" button when you're ready. 

If you haven't merged it by December 15th, I will go ahead and do it just to keep the repository clean!

**Pull request merged**
