### PR TITLE
Add nickhericks

### PR DESCRIPTION
**Pull request by nickhericks**
Add me!

### CODE REVIEW

**Comment by nickhericks** [comment]
@githubteacher can you assist with where I went wrong here?

**Comment by crichID** [comment]
@nickhericks actually, it isn't you! If you click on Details to the right where it says the `Travis CI build failed` you will see the following:

screen shot 2017-05-24 at 10 08 51 am

Basically, this user has removed their page. I actually fixed this already in #1011 but that pull request hasn't been merged yet so the checks will continue to fail until it is merged in to master. If you would like, you can also delete the file on your branch so the tests will pass.

**Comment by nickhericks** [comment]
@crichID I went into my branch and deleted the efoxweb file and now it passed! 
Many thanks! 😄

**Comment by nickhericks** [comment]
Closes #1012

**Comment by nickhericks** [comment]
@githubteacher by commenting "Closes #1012" above, shouldn't that close that issue? It looks like it is still open after about 10 minutes. Did I miss a step?

**Comment by crichID** [comment]
> by commenting "Closes #1012" above, shouldn't that close that issue? It looks like it is still open after about 10 minutes. Did I miss a step?

@nickhericks great question - the `closes #1012` should be in the first comment of the pull request when it is merged OR you can put it in the merge message. However, once it the pull request has been merged, you can't go back and add it.

**Comment by nickhericks** [comment]
@githubteacher ah, okay. Makes sense now. Thanks for your help today! In exchange for your great work, please feel free to take the rest of the day off. 😀

**Comment by crichID** [comment]
> In exchange for your great work, please feel free to take the rest of the day off.

:tada: Thank you @nickhericks - I need more students who give me the day off! Please send all of your friends :wink:

**Pull request merged**
