### PR TITLE
Added my GitHub handle

### PR DESCRIPTION
**Pull request by easpaas**

### CODE REVIEW

**Comment by a-a-ron** [comment]
Hey, i noticed you still might be having some issues. This is what you want your file to look like.

```
 ---
 githubHandle: YOUR-USERNAME
 pageUrl: YOUR-USERNAME.github.io
 timestamp: TODAYS-DATE-YYYY-MM-DD
 ---
```

Make sure you have no extra spaces at the beginning of each line and also make sure that you have a space after the `:`.

**Comment by a-a-ron** [comment]
This is what it should look like

```
 ---
 githubHandle: easpaas
 pageUrl: easpaas.github.io
 timestamp: 2017-03-10
 ---
```
The `TODAYS-DATE` was just a place holder for the actual date and the YYYY-MM-DD was an example of how to format the date.

**Comment by crichID** [comment]
@a-a-ron thank you for the awesome support! Your suggestions are :sparkles:

**Comment by easpaas** [comment]
@a-a-ron I receive a 404 error using easpaas.github.io as my pageURL. To my understanding I am receiving this error because that page does not exist? Do I have to include my pageURL that I have published before?

**Pull request closed without merging**
