### PR TITLE
Trying to add my page to the showcase.

### PR DESCRIPTION
**Pull request by okayhippo**
Adding my page.

### CODE REVIEW

**Comment by okayhippo** [comment]
@githubteacher I need help

**Comment by dipstar** [comment]
Hey 👋 @okayhippo the reason why the CI builds are failing is due to your okayhippo.github.io site not being online. Have a look at the instructions again about enabling the website in your repo settings. By the way, I am not @githubteacher Just thought I would help 😄

**Comment by okayhippo** [comment]
@dipstar I had a feeling, but I wasn't sure where to go, thanks! I'll check it out 😄

**Comment by okayhippo** [comment]
@dipstar Hey idk if you can help direct me where to go but I can't really figure it out 😢

**Comment by okayhippo** [comment]
@dipstar oh wait nevermind, I think I've got it 😛

**Comment by dipstar** [comment]
No problem. For reference, this might help https://guides.github.com/features/pages/

**Pull request merged**
