### PR TITLE
Add dmyers16.yaml file to _pages

### PR DESCRIPTION
**Pull request by dmyers16**

### CODE REVIEW

**Comment by dmyers16** [comment]
@githubteacher, any ideas why this isn't working?

**Comment by tkosaber** [comment]
Maybe you can add an 'ENTER' after the last   '---'.

**Comment by Vagacoder** [comment]
Two possible mistakes:
1. Need newline (ENTER) at the end of file, - add ENTER after second "---";
2. sneanrocky's link is not validate, remove his .yaml file.

**Comment by Justme764** [comment]
hey @dmyers16 you need to use 3 dots ... at the beginning and 3 dots .. at the end and then hit enter and it should pass. everybody user dashes ---  for some reason.  I had the same problem.  hope this helps.

**Comment by Justme764** [comment]
@dmyers16  below is the error from the details tab.  If you fix those errors you should get all green checks.  hope this helps

_pages/dmyers16.yaml
1:1       error    syntax error: expected the node content, but found '<document end>'
2:1       error    missing document start "---"  (document-start)
6:1       warning  too many blank lines (1 > 0)  (empty-lines)

**Comment by crichID** [comment]
@dmyers16 I went ahead and fixed the syntax issues in https://github.com/githubschool/on-demand-github-pages/pull/1842/commits/68317c470a125faa60046e0f099c2bacbdfaa5bf. Please take a quick look at the changes. Once the checks have finished, please feel free to click the big green **Merge pull request** button. If you haven't merged it by December 29th, I will go ahead and do it just to keep the repository clean!

**Pull request merged**
