### PR TITLE
add-username

### PR DESCRIPTION
**Pull request by ubet8932**

### CODE REVIEW

**Comment by ubet8932** [comment]
please help @githubteacher , I dunno what is wrong with my merge. Thank you.

**Comment by Justme764** [comment]
Hello @ubet8932 below is the info from the detail tab.  all you need to do is add a line to the end.

_pages/ubet8932.yaml
  5:4       error    no new line character at the end of file  (new-line-at-end-of-file)

**Comment by crichID** [comment]
@ubet8932 the advice @Justme764 gave is correct - you just need to  add a new line character at the end of the file and your tests should pass.

**Comment by Saichethan** [comment]
Please once again check your settings
Especially Travis CI settings make sure you turned them on for this repository

**Comment by brianamarie** [comment]
@ubet8932  I made some changes so the tests will pass. Once everything turns green, I'll go ahead and merge this in since it's been a few days and we want to keep the repository clean. 😄 ✨

**Pull request merged**
