### PR TITLE
Add travis file and yamllint configs

### PR DESCRIPTION
**Pull request by brianamarie**
@githubschool/training-team Thoughts on merging this in for a starter file?

### CODE REVIEW

**Comment by brianamarie** [comment]
❤️ @hectorsector for Yamale! 

Question about Yamale - it seems there are some binaries in our repository now for testing. 
1. Can we import these from somewhere else?
2. If not, should we add these to `.gitignore`?

**Comment by hectorsector** [comment]
Hm, you're right, @brianamarie. I did this pretty late let me try and play with it, I don't think we need the binaries as Travis will compile and run them on-the-fly. If I'm successful in running without it, then I will remove them and add them to the `.gitignore`.

**Comment by hectorsector** [comment]
> If not, should we add these to .gitignore?

👍 should be set now. I would not want to import yamale from somewhere else because I modified the code a bit to perform the following things that it didn't natively do:

1. Accept a directory of YAML files in addition to individual files.
1. Allow `---` above and below the YAML key-value pairs.

**Comment by hectorsector** [comment]
@brianamarie @githubschool/training-team can 🚢 with one approval.

**Comment by brianamarie** [comment]
@hectorsector Made some more changes; added tests for file endings (which may be unnecessary with yamale) and test for ensuring no files were added to root directory. 

It won't catch everyone, but should catch those that forget to add their file to the _pages directory. 

Re-mentioning training team for fresh eyes 👀  @crichID @hectorsector @beardofedu @hollenberry

**Comment by crichID** [comment]
@brianamarie do all of these files remain in the repository or should some of these be in a .gitignore

**Comment by brianamarie** [comment]
> @brianamarie do all of these files remain in the repository or should some of these be in a .gitignore

@crichID Good question! I _believe_ everything here can be in the main repository, but if it makes sense to add them to the `.gitignore` I'm all for that. Do you have any suggestions?

**Comment by hectorsector** [comment]
Looks great @brianamarie! I tested it a bit [on the `test-ci` branch](https://github.com/githubschool/on-demand-github-pages/commits/test-ci). 

@crichID I'm not sure what you mean but barring that I think we're ready to 🚢 this.

**Comment by crichID** [comment]
> I believe everything here can be in the main repository, but if it makes sense to add them to the .gitignore I'm all for that. Do you have any suggestions?

@brianamarie I was crossing up my conversations and thought some of these were files that resulted from the tests themselves. Ignore me and please feel free to :shipit:

**Pull request merged**
