### PR TITLE
adding mnemoniko's page

### LINKED ISSUE #1010: Add me as a collaborator
Thanks!

### PR DESCRIPTION
**Pull request by mnemoniko**
Adding a page
Closes #1010
Added new line at end to remove error
Also fixed the link

### CODE REVIEW

**Comment by mnemoniko** [comment]
@githubteacher I can't seem to parse this error.  Any suggestions?

**Comment by crichID** [comment]
@mnemoniko this one was tricky - I had to call in some reinforcements too :wink: 

First, I fixed the capitalization of `pageUrl`. When the test ran a second time, it found another student's URL was no longer valid which causes the checks to fail since it is checking all of the links. 🤞

**Comment by crichID** [comment]
@mnemoniko everything is passing! Please feel free to merge your pull request so the fix can be applied to master!

**Comment by mnemoniko** [comment]
@crichID Thanks so much!  I feel a bit better knowing it wasn't just a simple fix :smile:

**Pull request merged**
