### PR TITLE
Update silver-surfer94.yaml

### PR DESCRIPTION
**Pull request by silver-surfer94**

### CODE REVIEW

**Comment by silver-surfer94** [comment]
@githubteacher my pull requests fails the tests if I use  silver-surfer94.github.io and my website does not add to the website grid on the tutorial. Please help! 😢

**Comment by brianamarie** [comment]
Hi @silver-surfer94! When I go to silver-surfer94.github.io, I get a 404 page. Did you create a webpage in the first part of the tutorial? If so, do you know the URL for it?

**Comment by brianamarie** [comment]
If you have created your repository, please go to the repository **settings** and scroll down to the **pages** section. Using the drop-down, select the **master** branch to render your website. When you have finished this, your web page will display at the link shown at the top of the pages section.

**Comment by silver-surfer94** [comment]
@brianamarie here's the link: https://silver-surfer94.github.io/My-First-Project/. I have already used that one in the ymdl file, and it works, but the tutorial grid with the added websites does not update no matter how much i refresh the page.

**Comment by brianamarie** [comment]
@silver-surfer94 Ah, I understand. I just checked, and it's working for me. Sometimes it takes a few minutes to update, and sometimes even if it's updated on the backend, the previous version is cached in the browser. 
itworks


To see the refreshed page, try a hard refresh, clearing the cache, or opening it in another browser. Nice work! 😄

**Comment by silver-surfer94** [comment]
Ahhh I get it! I am on my way to being web famous. Many thanks, @brianamarie :+1:

**Comment by hectorsector** [comment]
@silver-surfer94 since it looks like you were able to merge in https://github.com/githubschool/on-demand-github-pages/pull/1073 and it works ✨ now, I'm going to go ahead and close this out. Congrats!

**Pull request closed without merging**
