### PR TITLE
Remccormick add page - corrected yaml

### PR DESCRIPTION
**Pull request by remccormick**
Remccormick add page - corrected yaml

### CODE REVIEW

**Comment by remccormick** [comment]
Will recheck syntax. Is this case sensitive?

**Comment by remccormick** [comment]
@githubteacher  can you see improper syntax in this .yaml file

**Comment by hectorsector** [comment]
@remccormick our tests check that all existing pages are still available so we don't leave broken links. That [was happening](https://travis-ci.org/githubschool/on-demand-github-pages/builds/421359550#L672) in this case. I removed the broken link and you should now be able to 🚢!

**Comment by remccormick** [comment]
@chrt @hectorsector - My thanks to you both! Wow - cool to see the workflow process unfold like this.

**Pull request merged**
