### PR TITLE
Adding a yaml file

### PR DESCRIPTION
**Pull request by JoelGeib86**

### CODE REVIEW

**Comment by Justme764** [comment]
@JoelGeib86  remove the 3 dashes at the top and bottom and use 3 dots ... instead

**Comment by Justme764** [comment]
@JoelGeib86  I had a hard time getting mine to work also.

**Comment by Justme764** [comment]
@JoelGeib86 here is a link to a video that help mine pass.  https://vimeo.com/201011288
hope it helps

**Comment by Justme764** [comment]
@JoelGeib86   I watched the video again and you need to change your file path to pins directory. remove page.  probably be easier to just watch the video.  Hope I have helped a small amount.  I'm learning too.

**Comment by crichID** [comment]
@JoelGeib86 I went ahead and fixed the syntax issues in https://github.com/githubschool/on-demand-github-pages/pull/1857/commits/793cae805e5a56baace47c16ba8f6553bb8712f1. Please take a quick look at the changes. Once the checks have finished, please feel free to click the big green **Merge pull request** button. If you haven't merged it by December 29th, I will go ahead and do it just to keep the repository clean!

**Pull request merged**
