### PR TITLE
add allsoppo yaml file

### PR DESCRIPTION
**Pull request by allsoppo**

### CODE REVIEW

**Comment by allsoppo** [comment]
@githubteacher any idea why my pull request keeps failing?

**Comment by beardofedu** [comment]
@allsoppo change your URL from the one you currently have to something that looks like this one:

`allsoppo.github.io/102-Repo/`

**Comment by allsoppo** [comment]
@githubteacher I changed the URL to the one you suggested, and it is still failing. Any other ideas?

**Comment by beardofedu** [comment]
@allsoppo looking at your build failure it would appear that you need to remove the `_pages` file that lists `antonshtunder.github.io` since that repository no longer exists. 

This is the exact file you need to delete: `_pages/antonshtunder.yaml`

**Comment by crichID** [comment]
@allsoppo your code looks perfect! Please go ahead and click the big green button below to **Merge pull request**. In an effort to keep things in this repository clean, I will merge this if it is still open on April 21st.

**Pull request merged**
