### PR TITLE
Added namedtoaster.yaml

### PR DESCRIPTION
**Pull request by namedtoaster**

### CODE REVIEW

**Comment by brianamarie** [comment]
Hi @namedtoaster! Try adding an extra line break at the end of the file to get the tests to pass. Let me know if you want any help!

**Comment by namedtoaster** [comment]
@brianamarie Apparently I need help lol. Is my pageUrl incorrect?

**Comment by brianamarie** [comment]
@namedtoaster Ah, yes, it looks like that URL is going to a 404. Do you have a different link from the first part of the activity?

**Comment by brianamarie** [comment]
@namedtoaster Maybe try replacing the URL with this: https://namedtoaster.github.io/practicegithub/

**Comment by namedtoaster** [comment]
@brianamarie Still not working 😢

**Comment by brianamarie** [comment]
@namedtoaster You're getting close!
- Try removing the https://, so the link is just `namedtoaster.github.io/practicegithub/`
- Make sure there's that extra line at the end

Props to you for sticking with it! ✨

**Comment by namedtoaster** [comment]
ay caramba

**Comment by brianamarie** [comment]
@namedtoaster 😂 You got this! That extra line break at the end **should** do the trick. 

fingers crossed

**Comment by namedtoaster** [comment]
@brianamarie I feel so silly haha. What does adding a line break do?

**Comment by brianamarie** [comment]
@namedtoaster Since the file is 'yaml', we have a test run called 'yamllint'. It checks to make sure the syntax is valid. Without it, it wouldn't play nice with the formatting language we use, called liquid.

**Comment by brianamarie** [comment]
@namedtoaster And - you're not silly. You wouldn't believe how many pull requests I've seen just today with the exact same thing. 😄

**Comment by namedtoaster** [comment]
@brianamarie haha well thanks for your help. This has been fun 😃

**Comment by namedtoaster** [comment]
🙌 🙌 🙌 🙌

**Comment by brianamarie** [comment]
Yay!!! 

yes

**Comment by namedtoaster** [comment]
I gotta say, I'm really loving this! As terrible as I am, I LOVE programming...or at least trying!

**Pull request merged**
