### PR TITLE
Create a yaml page to add my page to shared project space

### PR DESCRIPTION
**Pull request by ridsjin**

### CODE REVIEW

**Comment by ridsjin** [comment]
@githubteacher  Tried a nd played with newline and wat not but struggline. Please help close this.

**Comment by beardofedu** [comment]
@ridsjin I removed an extra space on line 5 that may have been causing issues. Waiting on checks to see if it passes. 👍

**Comment by beardofedu** [comment]
@ridsjin I deleted a `.yaml` file for a repository that no longer exists due to the user deleting it. Your tests should pass now.

**Comment by crichID** [comment]
@ridsjin your code looks perfect! Please go ahead and click the big green button below to **Merge pull request**. In an effort to keep things in this repository clean, I will merge this if it is still open on April 21st.

**Pull request merged**
