### PR TITLE
adding my page

### PR DESCRIPTION
**Pull request by jquiro12**

### CODE REVIEW

**Comment by jquiro12** [comment]
@githubteacher  Hi!! may you help me? i couldn't do this, this is my 8 attempt !

**Comment by maxa31** [comment]
Hey, my checks are also all failing. I noticed that you have also always used 
`https://yourname.github.io/` as the pageUrl. Have you tried `yourname.github.io` though? I thought of trying this.

**Comment by maxa31** [comment]
Changing it worked for me :)

**Comment by jquiro12** [comment]
you're right! thanks alot for you help!.

Have a good night!

**Pull request merged**
