### PR TITLE
added crlf

### PR DESCRIPTION
**Pull request by jphiggs**

### CODE REVIEW

**Review by jphiggs — COMMENTED** [review]
added crlf

**Comment by jphiggs** [comment]
added crlf

**Comment by jphiggs** [comment]
added crlf

**Review by jphiggs — COMMENTED** [review]
Requested change to final line

**Comment by CodesaurusRex** [comment]
@jphiggs made some changes your pull request can now be merged. There were a couple of issues so it would be worth looking through the changes and comments.

**Pull request closed without merging**
