### PR TITLE
add jv2301.yaml

### PR DESCRIPTION
**Pull request by jv2301**
What do you think @githubteacher?

### CODE REVIEW

**Comment by hollenberry** [comment]
Almost there @jv2301   !

Looks like you just need to add a new line to the bottom of your file.

If you need any help, please reach out and let us know if you have questions! 🎉

**Comment by JYang412** [comment]
I was wondering if it matter whether the new line character is windows, linux or mac style? @githubteacher

**Comment by hollenberry** [comment]
@JYang412 Oh, no problem! You can just edit it directly in the GitHub UI, without having to worry about OS!

**Comment by smithna-pra** [comment]
Thanks for this example @jv2301. I might have the exact same problem with my file!

**Comment by crichID** [comment]
@jv2301 I went ahead and fixed the syntax issues in https://github.com/githubschool/on-demand-github-pages/pull/1149/commits/e16a3ced99fbf24824e290a798cd6c0663cbc499. Please take a quick look at the changes. Once the checks have finished, please feel free to click the big green **Merge pull request** button. If you haven't merged it by July 7th, I will go ahead and do it just to keep the repository clean!

**Comment by jackgaoyichen** [comment]
close #1255 #1256

**Comment by jackgaoyichen** [comment]
closes #1256 #1255

**Pull request merged**
