### PR TITLE
add yaml file

### PR DESCRIPTION
**Pull request by SlodderWolf**
Hi everyone 👋 , they skip a step in the course. Dont forget to make an issue with "request push acces"

### CODE REVIEW

**Comment by wooorm** [comment]
@SlodderWolf It should be `pageUrl`, not `pageURL`!

**Comment by SlodderWolf** [comment]
@wooorm Thanks, but still doesn't working..

**Comment by SlodderWolf** [comment]
@githubteacher what do i wrong?

**Comment by wooorm** [comment]
It seems the repo of `trafalgarandre` was removed. You can remove their YAML file.

**Comment by SlodderWolf** [comment]
@wooorm Still a problem ..

**Comment by wooorm** [comment]
Uhuh. Now you need to get your code onto the new master (with the fix).

@theonejonahgold made a little description of that here: https://github.com/githubschool/on-demand-github-pages/pull/2169#issuecomment-363759313. Could you try and follow that?

**Comment by SlodderWolf** [comment]
@wooorm he he 👏

**Comment by wooorm** [comment]
Woohoo! 🎉

**Pull request merged**
