### PR TITLE
Adding catherinetran1's to page directory

### PR DESCRIPTION
**Pull request by catherinetran1**
This PR introduces ‘catherinetran1’ to directory of pages. Please review @githubteacher

### CODE REVIEW

**Comment by catherinetran1** [comment]
@brianamarie could you help me figure out why my checks have failed?

**Comment by MarieCrappe** [comment]
Hi @catherinetran1 
Your checks are failing because of other files (from previous contributors).
I'm working on it !

**Comment by MarieCrappe** [comment]
Hi @catherinetran1 you can now try again. You need to take into account the new version of the project for that, so make sure to do "git pull" and then to commit and push again, and it should be all fine

**Comment by catherinetran1** [comment]
@MarieCrappe Thank you for the update!

**Pull request closed without merging**
