### PR TITLE
githubhandle added wtb2015

### PR DESCRIPTION
**Pull request by wtb2015**
githubhandle added wtb2015

### CODE REVIEW

**Comment by wtb2015** [comment]
@githubteacher what do you think ?

**Comment by wtb2015** [comment]
@githubteacher  Help ! any idea why this fails ?

**Review by wtb2015 — COMMENTED** [review]
moved travis.yml to /_pages/travis.yaml and added test back into code.

**Review by beebus — APPROVED** [review]

**Comment by beebus** [comment]
Too many conflicts and too many changes being made. Too confusing of a story. Let's start fresh.

**Pull request closed without merging**
