### PR TITLE
Wendcoin goes to school!

### PR DESCRIPTION
**Pull request by wendcoin**

### CODE REVIEW

**Comment by Aotoge** [comment]
Heya @wendcoin! Seems like you don't have any pages up yet, try adding an index.html file to your USERNAME.github.io repository and try again. :smile:

**Comment by wendcoin** [comment]
Thank you so much for e-mailing me.  I have added index.html.  I am a total novice at cryptocurrency and coding.  I have been reading and researching everything I can find on the subject.  It would be very helpful if someone was available to help me understand the best way to buy seed node and how to get daemon to print and generate information needed.  Thank you on behalf of wendcoin,

**Comment by Justme764** [comment]
Hello @wendcoin  your file has dashes instead of dot.  replaces the first 3 dash --- with 3 dot ... do that to the last line also and make sure you have no extra spacing.  it should then pass.  if not ask the teacher. hope this helps.

**Comment by Justme764** [comment]
@wendcoin  below is the info from the details tab above. here is the error I found.  It appears there is something wrong with you page address.  I'm not really sure i'm pretty new also. I would ask the @githubteacher Can you help?  Hope we both can learn something and hope the teacher gets back, sometime I get no answer when I ask.  Going to bed.  will check back tomorrow.  Good luck!!!!

*  External link Wendcoin.github.io failed: 404 No error
E
===============================================================================
Error: test_htmlvalidation(TestHTMLValidation)
: RuntimeError: HTML-Proofer found 1 failure!
/home/travis/.rvm/gems/ruby-2.2.2/gems/html-proofer-3.7.5/lib/html-proofer/runner.rb:167:in `print_failed_tests'
/home/travis/.rvm/gems/ruby-2.2.2/gems/html-proofer-3.7.5/lib/html-proofer/runner.rb:48:in `run'
tests/test_HTML.rb:13:in `block (2 levels) in test_htmlvalidation'
     10:       [
     11:         f["pageUrl"],
     12:       ].each do |s|
  => 13:         assert_not_nil(HTMLProofer.check_links([s]).run, path)
     14:       end
     15:     end
     16: 
tests/test_HTML.rb:12:in `each'
tests/test_HTML.rb:12:in `block in test_htmlvalidation'
tests/test_HTML.rb:8:in `each'
tests/test_HTML.rb:8:in `test_htmlvalidation'
===============================================================================
Finished in 12.833289493 seconds.
1 tests, 67 assertions, 0 failures, 1 errors, 0 pendings, 0 omissions, 0 notifications
0% passed

**Comment by wendcoin** [comment]
Thank you so much for helping.  I know you are busy.  Your time means a lot to me.  :)

**Comment by Justme764** [comment]
@wendcoin   try adding a line to you page after the 3 dashes hit the enter and see if that make your page work.

**Comment by crichID** [comment]
@wendcoin it looks like the tests are failing because your web page no longer exists or pages has not been enabled on the repository. 

If you have created your repository, please go to the repository **settings** and scroll down to the **pages** section. Using the drop-down, select the **master** branch to render your website. When you have finished this, your web page will display at the link shown at the top of the pages section.

**Comment by wendcoin** [comment]
Gee thanks.  I followed your instructions and hope that I have successfully rendered it.  Thank you.  :)

**Comment by brianamarie** [comment]
Hi @wendcoin! I see the tests are still failing. When I check the URL that you have linked in this file, http://wendcoin.github.io/, it shows 404. Are you sure this URL is correct?

**Comment by brianamarie** [comment]
@wendcoin It looks like the actual URL is here: https://wendcoin.github.io/wend.github.io/

There are two things you could do. You could either: 
- [Rename the repository](https://help.github.com/articles/renaming-a-repository/) to be **wendcoin.github.io** instead of **wend.github.io**
OR 
- Update this file so the url points to `wendcoin.github.io/wend.github.io/` instead of `wendcoin.github.io`. 

Let me know if you'd like any help! If this is still around by the end of the week I'll go ahead and make the changes for you so we can keep this repository clean. 😄

**Pull request merged**
