### PR TITLE
Public page

### PR DESCRIPTION
**Pull request by jvjishnu**
Content to make page public. Check for errors and merge.

### CODE REVIEW

**Comment by jvjishnu** [comment]
@brianamarie  Hi, can you please tell me whats wrong here, I followed the steps but it won't pass the checks.

**Comment by brianamarie** [comment]
@jvjishnu One of the tests is checking that the URL is valid. Right now, jvjishnu.github.io goes to a 404 instead of a site. Once this is a working link, the tests should pass. Does that help?

**Comment by jvjishnu** [comment]
@brianamarie  Thank You for the response, do I need to do something about it? or will it happen automatically after some time? Or should i change my URL? Because jvjishnu.github.io/desktopGit/ is a valid page.

**Comment by brianamarie** [comment]
@jvjishnu Try editing the file and replacing the current URL with jvjishnu.github.io/desktopGit/, it should pass 👍

**Comment by jvjishnu** [comment]
@brianamarie I've changed it, the checks are going on. Thank you :smile:

**Comment by jvjishnu** [comment]
@brianamarie  It worked. Thank you so much :smile:

**Pull request merged**
