### PR TITLE
Add page & remove file

### PR DESCRIPTION
**Pull request by AstrildW**
- add AstrildW page
- remove file containing socsuc.github.io/Test

### CODE REVIEW

**Comment by AstrildW** [comment]
@githubteacher hey 😸 could you please take a look? I re-did everything according to your notes (old pull request is closed)

As before I was trying to complete this task without using GitHub Desktop. New line is added and extra .txt extention removed now. From what I understood I was supposed also to delete file in _pages containing socsuc.github.io/Test from my branch before pulling request. Is it right ❔ 

But the checks wont pass 😿 
Could you please help me with that?

**Comment by crichID** [comment]
@AstrildW this looks correct but for some reason Travis isn't building this branch. Let me do some more investigation to see if I can understand why!

**Comment by crichID** [comment]
A big thanks to @beardofedu for spotting the issue. The builds had been disabled 😊 --- I didn't even think to check something so simple. It looks like the tests were still waiting for a newline character. I added one so let's see if they pass now!

**Comment by AstrildW** [comment]
Thanks @crichID and @beardofedu for your help
unfortunately checks have failed again :confused:

**Comment by crichID** [comment]
@AstrildW according to the tests it is looking for a `\n` at the end of the file. I added it so let's see if it passes now.

**Comment by brianamarie** [comment]
@AstrildW There were some broken links on other pages that were breaking the build. I fixed them and merged the changes into this branch. Hopefully, the tests will pass and you'll be able to merge. 🤞

**Comment by AstrildW** [comment]
Thank you @brianamarie @crichID @beardofedu
I dont have any more ideas 😫 Do you?

**Comment by brianamarie** [comment]
@AstrildW Your file is fine, I think the errors are coming from others. Don't worry, you're doing great! Thank you for your patience and for sticking around. 😄 I will make sure that we get this figured out.

**Comment by brianamarie** [comment]
Woohoo! @AstrildW, you're good to go! 👍 🚢

**Comment by AstrildW** [comment]
Thank you!!! 🍾

**Pull request merged**
