### PR TITLE
Add derechoandrea pages to class repository

### PR DESCRIPTION
**Pull request by derechoandrea**
This PR introduces 'derechoandrea'  to the directory of pages. Please review @githubteacher.

### CODE REVIEW

**Comment by crichID** [comment]
@Shutsen please be careful not to close pull requests you did not open. We want everyone to have the opportunity to complete the activity from beginning to end.

**Comment by crichID** [comment]
@derechoandrea it looks like the tests are failing because your web page no longer exists or pages has not been enabled on the repository. If you have created your repository, please go to the repository **settings** and scroll down to the **pages** section. Using the drop-down, select the **master** branch to render your website. When you have finished this, your web page will display at the link shown at the top of the pages section.

**Comment by derechoandrea** [comment]
@githubteacher help please

**Comment by crichID** [comment]
@derechoandrea when I go to https://derechoandrea.github.io/gitderechohubandrea/, I am getting a 404 page. In order for this to be a valid link, you would have a repository at: https://github.com/derechoandrea/gitderechohubandrea. If you can point me to the website repository you made for this activity, I can help you fix the link!

**Pull request closed without merging**
