### PR TITLE
adding malam04's page

### PR DESCRIPTION
**Pull request by malam04**

### CODE REVIEW

**Comment by malam04** [comment]
@githubteacher Cannot understand why the Travis CI build is failing. Any help?

**Comment by CodesaurusRex** [comment]
This seems to be either a problem with Travis CI or the code that the GitHub tutorial is asking us to enter. Very few people's tests have passed and for numerous different errors. Looks like it's a bug. Your code is exactly what the tutorial has asked us to enter.

**Comment by malam04** [comment]
ahh that's a relief, it was frustrating trying to figure out what wasn't passing the tests.

**Comment by arr99** [comment]
尊敬的领导你好你辛苦了。你一天给我发很多信息我看不明白你是不是给我找回我的康福ID？我看不懂如果是你看看需要多少费用我付款给你你发我邮箱可以吗？谢谢




------------------ 原始邮件 ------------------
发件人: "teacherbot[bot]"<notifications@github.com>;
发送时间: 2018年4月18日(星期三) 上午6:07
收件人: "githubschool/on-demand-github-pages"<on-demand-github-pages@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>; 
主题: Re: [githubschool/on-demand-github-pages] adding malam04's page(#2830)




 Congratulations, you have finished this course. Please take a moment to tell us what you think of this course. If you completed the course with GitHub Desktop, click here. If you used the command line, click here.
 
Also, please remember to delete your branch if you haven't done so already.

**Pull request merged**
