### PR TITLE
Schiavi13 add page

### PR DESCRIPTION
**Pull request by Schiavi13**
changed caps

### CODE REVIEW

**Comment by Schiavi13** [comment]
@githubteacher I don't know what is wrong with my file

**Comment by johnstond** [comment]
There is nothing wrong with your file. 
  *  External link 1dhiman.github.io failed: 301 SSL connect error
This error is very common in this course.

**Comment by johnstond** [comment]
@Schiavi13 
The time to merge is now!

**Comment by Schiavi13** [comment]
@johnstond Thanks a lot!

**Pull request merged**
