### PR TITLE
adding page

### PR DESCRIPTION
**Pull request by specimenz**
adding yaml file

### CODE REVIEW

**Comment by lizurdlunker** [comment]
You have to fix or delete any offending pages that keep the ci tests from passing.  In this case it is the 'dunn-cwu.yaml' page

**Comment by specimenz** [comment]
@lizurdlunker Thanks.

**Comment by specimenz** [comment]
@githubteacher how do I determine who is member of the training team?

**Comment by johnstond** [comment]
@specimenz 
Ready to merge.

**Pull request closed without merging**
