### PR TITLE
add 'brigitta-lee/test-website' to pages directory

### PR DESCRIPTION
**Pull request by brigitta-lee**

### CODE REVIEW

**Comment by brigitta-lee** [comment]
@githubteacher  Not quite sure what is happening here.  Can you help?

**Comment by crichID** [comment]
@brigitta-lee it if you click on `Details` next to where it shows the failing tests:

screen shot 2017-03-16 at 8 59 06 am

You can scroll down until you find the failing test:

screen shot 2017-03-16 at 8 58 09 am

In this case, your tests are failing because another student deleted their website and this is causing the HTMLProofer test to fail. I am going to delete their file and we will let the tests run again.

**Comment by crichID** [comment]
@brigitta-lee hooray :tada: it looks like your tests are passing now and you can click the big green **Merge pull request** button. Great work!

**Comment by brigitta-lee** [comment]
@githubteacher Thanks a lot!

**Pull request merged**
