### PR TITLE
Added info

### PR DESCRIPTION
**Pull request by Jdomingo1006**

### CODE REVIEW

**Comment by Jdomingo1006** [comment]
Wow!

**Comment by HanochShi** [comment]
Hello,
I want to give you some ideas.
The URL in your file is unavailable. May that's why you can't pass the test. In my opinion, you should enter a URL like this : YOURUSERNAME.github.io/REPONAME
And you should ensure that there is a available page of the repository in the URL

**Comment by brianamarie** [comment]
@Jdomingo1006, @HanochShi is right, sadly the webpage doesn't exist. Since this file is not valid per the examples in the course, I am going to go ahead and close this Pull Request. If you would like to complete the activity, please feel free to re-open this Pull Request or start again. If you have any questions, please let us know!

**Comment by Jdomingo1006** [comment]
my "YOURUSERNAME.github.io/REPONAME" is working. Now im not entirely sure how im able to fix it with the github desktop.
Thank you

**Comment by beardofedu** [comment]
@Jdomingo1006 it looks like the tests are failing because your web page no longer exists or pages has not been enabled on the repository. If you have created your repository, please go to the repository **settings** and scroll down to the **pages** section. Using the drop-down, select the **master** branch to render your website. When you have finished this, your web page will display at the link shown at the top of the pages section. I am going to go ahead and close this pull request since your page is not currently enabled. If you would like to finish this activity, please feel free to re-open this pull request after you have enabled pages on your repository.

**Comment by beebus** [comment]
Keep getting the same Travis CI error:

Screenshot from 2019-09-03 04-48-42

$ rvm use **2.2.2** --install --binary --fuzzy
$ export BUNDLE_GEMFILE=$PWD/Gemfile
ruby.versions
$ ruby --version
install.bundler
58.19s$ bundle install --jobs=3 --retry=3 --deployment
before_script.1
1.84s$ pip install --user yamllint
before_script.2
1.23s$ pip install --user yamale
1.38s$ **gem install html-proofer**
Fetching: mercenary-0.3.6.gem (100%)
Successfully installed mercenary-0.3.6
Fetching: mini_portile2-2.4.0.gem (100%)
Successfully installed mini_portile2-2.4.0
Fetching: **nokogiri-1.10.4.gem** (100%)
ERROR:  Error installing html-proofer:
	**The last version of nokogiri (~> 1.9) to support your Ruby & RubyGems was 1.9.1. Try installing it with `gem install nokogiri -v 1.9.1` and then running the current command again
	nokogiri requires Ruby version >= 2.3.0. The current ruby version is 2.2.0.
The command "gem install html-proofer" failed and exited with 1 during .**

Possible solutions:
1. Increase the ruby version to 2.3.0 in the .travis.yml file so that nokogiri installs correctly and html-proofer installs correctly.
2. Do not install html-proofer.
3. It's ambiguous whether or not installing an earlier version of nokogiri, `gem install nokogiri -v 1.9.1` before installing html-proofer, would resolve the situation. Nokogiri might always need Ruby version >= 2.3.0 now.

A normal user / collaborator will not have the permissions to make these change(s). This change would have to be made by an owner or admin of the repo.

**Comment by brianamarie** [comment]
cc @hectorsector 👀 for comms duty

**Comment by hectorsector** [comment]
👋 @beebus this repository is no longer in use, but you can still learn about [GitHub Pages](https://lab.github.com/githubtraining/github-pages) and [Continuous Integration with Travis CI](https://lab.github.com/githubtraining/continuous-integration-with-travis-ci) on Learning Lab!

**Pull request closed without merging**
