### PR TITLE
tkosaber

### PR DESCRIPTION
**Pull request by tkosaber**

### CODE REVIEW

**Comment by tkosaber** [comment]
Could you tell me what is 'The Travis CI build failed?' @hollenberry 
Thank you very much

**Comment by tkosaber** [comment]
Thank you so much for your help @dmyers16 
 it still has trouble in my file named 'tkosaber-add-newline'.
It looks like no problems but it just tells me that'The Travis CI bulid failed'.

**Comment by tkosaber** [comment]
Finish get though.

**Comment by Justme764** [comment]
@tkosaber  remove the 3 dashes --- and replace with 3 dots ...  when you open your file look at the top left and you will see they use 3 dots.  hope this helps.

**Comment by tkosaber** [comment]
@Justme764 Hello!Thanks for your help.
I finished it the day before yesterday, I just created a new repository and a new branch ,then making it.
It seems that the file's name has troblem,so make sure "YOUR-NAME.yaml".
If you click the "Details" you will find that "seanrocky.github.io" falied,Maybe remove it will help,for me i just created a new repository .If you couldn't get though it,Try as what i said may useful.
Thank you ,have a good day.

**Comment by crichID** [comment]
@tkosaber it looks like the build  was failing  because you had an extra file that was linking to a page  that did not exist (tkosaber.github.io/myweb). I have removed that file so the tests **should** pass now. I will check back in as soon as things finish up!

**Pull request merged**
