### PR TITLE
Adding jessiegouw.yaml to master

### PR DESCRIPTION
**Pull request by jessiegouw**
Added github name, link and my current timestamp

### CODE REVIEW

**Comment by jessiegouw** [comment]
@githubteacher I don't get what is wrong with this 😢

```yaml
---
githubHandle: jessiegouw
pageUrl: jessiegouw.github.io
timestamp: 2018-02-06
---
```

**Comment by wooorm** [comment]
@jessiegouw From the logs, it looked like there were a few things from other people that didn’t work. It had probably nothing to do with you!

Could you try updating the timestamp to today? That should make Travis run again!
You can do that by clicking the pencil icon above your file, let me know if I can help!)

Related: https://github.com/githubschool/on-demand-github-pages/pull/2173

**Comment by jessiegouw** [comment]
@wooorm Ok, **HELP** please. I have absolutely no idea what to do now :(

**Comment by theonejonahgold** [comment]
Hey @jessiegouw. I have a fix for you.
1. Go to the project folder inside your terminal
2. Type `git merge origin/master`
3. (If vim (the text editor) doesn't close automatically, type `:wq` and press enter)
4. Check the `git status` to see if there aren't any uncommited files
5. Push to origin
6. Keep an eye on this pull request, as the tests will be running immediately after the push

Hope this is clear enough. If you need anymore help you can slack me @ jonahgold :)

**Comment by jessiegouw** [comment]
@theonejonahgold Thanks for the help!

But everything is up-to-date according to my terminal. I even checked out to the master branch and tried to merge, but it's all up-to-date. Soooo yeah :(

**Comment by wooorm** [comment]
Did you `git fetch` and `git pull`?

**Comment by wooorm** [comment]
🎉

**Comment by jessiegouw** [comment]
🎉 🎉  **THANKS** @theonejonahgold & @wooorm

**Pull request merged**
