### PR TITLE
Add patrascuandrei to _page directory

### PR DESCRIPTION
**Pull request by Patrascu-Andrei**
This PR intorduces 'patrascu-andrei' to the directory of pages. Please review @githubteacher!

### CODE REVIEW

**Comment by beardofedu** [comment]
@Patrascu-Andrei It doesn't appear that your website is loading. Are you sure GitHub Pages is enabled on your repository?

**Comment by beardofedu** [comment]
@Patrascu-Andrei Also, please remove the `https://` from your links.

**Comment by crichID** [comment]
@Patrascu-Andrei I remove the extra file with the broken link. The only thing remaining is to clean up the https:// from the URL in the file. Once you have done that, please feel free to press the big green button and merge the pull request. If you have any questions, please let us know. If this hasn't been fixed by April 21st, we will go ahead and close this to keep the repo clean.

**Comment by Patrascu-Andrei** [comment]
Finally! thank you @crichID

**Pull request merged**
