### PR TITLE
Add CI validation for timestamp field

### PR DESCRIPTION
**Pull request by brianamarie**
This pull request adds another test for validation of file contents, focusing on the timestamp.

@crichID @hectorsector @hollenberry @beardofedu for awareness and trying to break it. 🔨

### CODE REVIEW

**Comment by ONightPerson** [comment]
Looks great! 👍

**Comment by ovcharenko-di** [comment]
good job!

**Comment by hectorsector** [comment]
@brianamarie should `2016-10-7` work for October 7, 2016? If so, 👍 otherwise, that's passing when it shouldn't. 

Test | Expected | Actual
--- | --- | ---
`YYYYMM-DD` | ❌ Fail | [❌ Fail](https://travis-ci.org/githubschool/on-demand-github-pages/builds/189026147)
`YYYY-MMDD` | ❌ Fail | [❌ Fail](https://travis-ci.org/githubschool/on-demand-github-pages/builds/189026564)
`YYYY MM DD` | ❌ Fail | [❌ Fail](https://travis-ci.org/githubschool/on-demand-github-pages/builds/189026938)
`YYYY-DD-MM` | ❌ Fail | [❌ Fail](https://travis-ci.org/githubschool/on-demand-github-pages/builds/189027497)
`DD-MM-YYYY` | ❌ Fail | [❌ Fail](https://travis-ci.org/githubschool/on-demand-github-pages/builds/189027964)
`MM-DD-YYYY` | ❌ Fail | [❌ Fail](https://travis-ci.org/githubschool/on-demand-github-pages/builds/189028032)
`YY-MM-DD` | ❌ Fail | [❌ Fail](https://travis-ci.org/githubschool/on-demand-github-pages/builds/189028402)
`YYYY-MM-D` | ❌ Fail | [✔️ Success](https://travis-ci.org/githubschool/on-demand-github-pages/builds/189028648) 🔫 
`YYYY-MM-DD` | ✔️ Success | [✔️ Success](https://travis-ci.org/githubschool/on-demand-github-pages/builds/189028110)

**Comment by brianamarie** [comment]
Alright - Thank you @hectorsector for bringing that up!

Pinging @nathos & @kylemacey because they were helping me troubleshoot this earlier.

**Problem: single digit dates at the end will pass the test, like `YYYY-MM-D`**

**Things I've tried:**

```
assert_true(Date.valid_date?(y.to_i, m.to_i, d.to_i), path)
```

```
assert_not_nil(Date.parse(s.to_s), path)
```

```
assert_not_nil(s.to_s[/(201\d{1}-(0[1-9]|1[0-2])-[0-3]{1}\d{1})/], path)
```

Any thoughts on possible other solutions?

**Comment by kylemacey** [comment]
sorry, maybe try something like this:

```ruby
# define this at the top of your test
def is_date?(str)
  begin
    Date.strptime(str.to_s, '%Y-%m-%d')
    true
  rescue ArgumentError
    false
  end
end

assert_true(is_date?(s), path)
```

**Comment by kylemacey** [comment]
So, looking into this a bit more, YAML is always going to parse dates in that format (`'%Y-%m-%d'`), so we can just validate that YAML recognized the date format. This will allow single-digit months and days, but that's ok, because YAML knows how to handle that (and ruby is doing the work on the jekyll side, so we can trust this). Commit coming up shortly

**Comment by brianamarie** [comment]
@kylemacey I applied the patch and then corrected a pin that I know was inaccurate, but still the test fails. 😢

**Comment by kylemacey** [comment]
Looks like `assert_true` is not an available method. Try changing that to just `assert`

**Comment by brianamarie** [comment]
🎉  All of the ✨  to @kylemacey and @nathos! Thank you both! 

One last sanity check - I'll merge this with 1 👍  🌈

**Comment by nagasawy** [comment]
Looks great!

**Comment by AAR1995** [comment]
Good stuff!

**Pull request merged**
