### PR TITLE
Second try to add my page

### PR DESCRIPTION
**Pull request by MarieCrappe**

### CODE REVIEW

**Comment by MarieCrappe** [comment]
In order to pass the continuous integration checks, I had to make a few changes to past contributions of other users based on the error messages that were triggered.
I added a line at the end of the yaml files and/or corrected the format of the URL for :  
- @fongj2 
- @keithhc2 
- @lydebacle 
- @shloot72 
Also, I removed the yaml file of @nadelros and @lydebacle from the root repository as they should only be located in the _pages folder.
Finally, I also removed the HTML document added by @shloot72 in the _pages folder.

**Comment by MarieCrappe** [comment]
I also had to change URL format of @xDlaugh 
For information, the URL format should be yourUserName.github.io (so no http)

**Comment by MarieCrappe** [comment]
All checks by Travis CI are now passing again !  :smile: :trophy: @catherinetran1

**Comment by xDlaugh** [comment]
Thanks!

**Pull request merged**
