### PR TITLE
Try to fix pins in master that are passing tests

### PR DESCRIPTION
**Pull request by brianamarie**
This PR edits pins that are already merged into master for some reason that are not passing the existing test suite.

### CODE REVIEW

**Comment by MarieCrappe** [comment]
Is there a way to prevent people from merging when tests are not passing ? Because this is what is happening @brianamarie

**Comment by brianamarie** [comment]
@MarieCrappe We have protected branches enabled so that tests must be passing before merging is allowed, but that seems to not be working.

It may have to do with a few pull requests that included deleted tests, so then the tests didn't run and they were allowed to merge. 

It'd be great if we could set it up so the tests weren't able to be deleted, but other code could be changed. Do you have any thoughts on how we could do this? 🤔 

cc/ @swinton

**Comment by MarieCrappe** [comment]
@brianamarie what about adding the test files to gitignore ? That's definitely not a perfect solution but it may help a little.

I don't have anything better in mind for now...

**Comment by brianamarie** [comment]
@MarieCrappe That's a good idea, I'm going to look into that. 

Also - I'm super impressed with how active you've been in this repository helping everyone get their contributions all lined up! If you don't mind sending an email to services@github.com with your shipping, I'd love to send a something your way as a thank you. 😄

**Comment by MarieCrappe** [comment]
@brianamarie That's really too kind of you !

Did you take part in building the training courses ? I'm just starting on GitHub and they've helped me a lot so I should be the one thanking you :smile: 

And that's great, required status checks are working again now :+1:

**Comment by brianamarie** [comment]
I'm glad that they've been helpful!!! Yes, I'm a member of the GitHub Training team. We all worked together to build these and are building more. 

My head is still spinning on why the required status checks weren't working for a time, but we're looking into that, as well as adding the travis file to the gitignore and the possibility of some tests being stored as submodules.

**Pull request merged**
