### PR TITLE
Update Phillangin.yaml

### PR DESCRIPTION
**Pull request by Phillangin**

### CODE REVIEW

**Comment by eugelogic** [comment]
Hello @Phillangin,

Good job so far.

The Travis CI is throwing a couple of errors:
1 - the file appears to be empty
2 - invalid date format, please make sure that is using this format: TODAYS-DATE-YYYY-MM-DD

Let us know how you get on.

**Comment by beardofedu** [comment]
@Phillangin you don't have a file in this PR so there is nothing for Travis to test against.

**Comment by crichID** [comment]
@Phillangin this PR is actually merging against a branch other than master. You will want to merge against master to add your page to the site. I am going to go ahead and switch the base branch to see if we can fix it :wink:

**Comment by crichID** [comment]
@Phillangin I went ahead and fixed the syntax issues in https://github.com/githubschool/on-demand-github-pages/pull/733/commits/47cf23e94e4e828076fa7dbc08dabf4966b7c01a. Please take a quick look at the changes. Once the checks have finished, please feel free to click the big green **Merge pull request** button. If you haven't merged it by April 21st, I will go ahead and do it just to keep the repository clean!

**Pull request merged**
