### PR TITLE
Add maikxx.yaml

### PR DESCRIPTION
**Pull request by Maikxx**

### CODE REVIEW

**Comment by wooorm** [comment]
@Maikxx It looks like your website isn’t online?

**Comment by wooorm** [comment]
@Maikxx Hey, this is still broken right? 🤔

**Comment by Maikxx** [comment]
Hey! I will check it tonight. Can't see it this quickly what is wrong.

**Comment by wooorm** [comment]
@Maikxx Well, there’s no repository here! https://github.com/maikxx/maikxx.github.io

**Comment by Maikxx** [comment]
[Updated link](Maikxx.github.io)

**Comment by wooorm** [comment]
@Maikxx Now you just need to push a change, so Travis runs again. You could maybe change the timestamp?

**Comment by Maikxx** [comment]
I did the assignment over again, with every step followed at the thumb, and it failed building again. #2310 It is so weird.

**Pull request closed without merging**
