### PR TITLE
jessiemasonx.yaml toegevoegd

### PR DESCRIPTION
**Pull request by jessiemasonx**
Adding webpage to master

### CODE REVIEW

**Comment by jessiemasonx** [comment]
I would like some help. What does 'syntax error: mapping values are not allowed here' mean? @githubteacher

**Comment by wooorm** [comment]
I think it’s because you start each line with one space! Could you remove those and try again?

**Comment by wooorm** [comment]
There was an error in another file, which was just fixed (https://github.com/githubschool/on-demand-github-pages/pull/2285).
If you update your timestamp to today, I think you’ll get a green light from Travis!

**Comment by wooorm** [comment]
😭 I forgot one thing 😭

Now you need to get your code onto the new master (with the fix).

@theonejonahgold made a little description of how to do that here: https://github.com/githubschool/on-demand-github-pages/pull/2169#issuecomment-363759313. Could you try and follow that?

**Comment by jessiemasonx** [comment]
omg . THANKS!! 🎉

**Comment by wooorm** [comment]
Woohoo!

**Pull request merged**
