### PR TITLE
Add my page to the class repo

### PR DESCRIPTION
**Pull request by yfCanada**

### CODE REVIEW

**Comment by brianamarie** [comment]
Hi @yfCanada! Looks like there are a few minor changes.
- Erase the `.txt` at the end of the file name
- Make sure the text on like 1 and like 5 is `---` 
- Erase https:// from the beginning of the URL

Let me know if you need any help!

**Comment by yfCanada** [comment]
Hi @brianamarie  Yes, I need help.  After I fix the yfCanada.yaml file at local depo and cmimit the change. I was going to do "pull request" but couldn't.   At the same place of "pull request" button, it is "view pull request #516" and leads me here.  How do I proceed? Thank you!

**Comment by brianamarie** [comment]
Hi @yfCanada! It sounds like you're using GitHub Desktop. It won't let you open a new pull request since this one already exists. Do you see anything to 'sync' or 'push' your changes? The changes are local, but you need to get them up to GitHub.com on the 'remote' repository.

**Comment by yfCanada** [comment]
Hi @brianamarie , I did sync and request new pull and it still doesn't pass the checks. What should I fix next? Thank you!

**Comment by brianamarie** [comment]
Hi @yfCanada! It looks like the file name still isn't quite right. It's showing as ending with `.yaml.txt` instead of just `.yaml`. [Here are some instructions for how to rename a file in the GitHub UI](https://github.com/blog/1436-moving-and-renaming-files-on-github).

**Pull request merged**
